
spring:
  profiles:
    active: "dev"
    include:
      - "config"

logging:
  pattern:
    level: "request-id=[%X{request-id}] remote-ip=[%X{remote-ip}] %5p"

---
spring:
  profiles: dev

  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      username: ${DB_USER:}
      pass: ${DB_PASS:}
      database: app-mutant-validator

logging:
  level:
    com:
      hvs:
        mutant: DEBUG


server:
  tomcat:
    max-threads: 500

---
spring:
  profiles: test

  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      username: ${DB_USER:}
      pass: ${DB_PASS:}
      database: app-mutant-validator

logging:
  level:
    com:
      hvs:
        mutant: INFO
  pattern:
    level: "request-id=[%X{request-id}] remote-ip=[%X{remote-ip}] %5p"

server:
  tomcat:
    max-threads: 500