version: "3.7"
services:
  mutant-app:
    image: ${IMAGE}
    links:
      - database
    ports:
      - target: 8080
        published: "${PUBLISH_PORT}"
        protocol: tcp
        mode: ingress
    environment:
      DB_HOST: database
      DB_PORT: 27017
      SEQUENCES: ${SEQUENCES}
      NUCLEOTIDE_NUMBER: ${NUCLEOTIDE_NUMBER}
      DEBUG: ${DEBUG}
  database:
    image: mongo:4.4.0
