

on: [push]


name: Deploy to server ssh

jobs:
  deploy:
    name: Deploy service
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "$EC2_AWS_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          echo "$SSH_HOST_EC2" > ~/.ssh/known_hosts
        shell: bash
        env:
          EC2_AWS_KEY: ${{secrets.EC2_AWS_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_HOST_EC2}}
          SSH_HOST_EC2: ${{ github.workspace }}/../private.key

      #- name: Deploy with rsync
      #  run: rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/app-mutant-validator

      - name: Deploy Service
        run: ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -f 'cd ~/app-mutant-validator && docker-compose up'
