

on:
  release:
    types: [ created ]

name: Deploy to server ssh

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "$EC2_AWS_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_HOST_EC2" > ~/.ssh/known_hosts
        shell: bash
        env:
          EC2_AWS_KEY: ${{secrets.EC2_AWS_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_HOST_EC2}}
          SSH_HOST_EC2: ${{ github.workspace }}/../private.key
